# Generated by Django 5.0.8 on 2026-01-13 16:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('dacdb464-c3cc-41fe-b6b8-80084e90c023'), editable=False, primary_key=True, serialize=False),
        ),
    ]
