# Generated by Django 5.0.8 on 2026-01-16 10:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_id_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d988f340-25d8-4537-a5b7-3ac8d32f8390'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cea50423-106e-4578-a3c2-48a90bfd19a6'), editable=False, primary_key=True, serialize=False),
        ),
    ]
