# Generated by Django 5.0.8 on 2026-01-16 10:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_address_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('836a2089-0275-41d7-9b96-cbe1f6d89bfd'), editable=False, primary_key=True, serialize=False),
        ),
    ]
