# Generated by Django 5.0.8 on 2026-01-16 16:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_address_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('45b120cc-3615-4d33-8308-3ff5ce1abede'), editable=False, primary_key=True, serialize=False),
        ),
    ]
