# Generated by Django 5.0.8 on 2026-01-16 16:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('78f03c06-4471-4d5f-952f-eee68d369ed3'), editable=False, primary_key=True, serialize=False),
        ),
    ]
