# Generated by Django 5.0.8 on 2026-01-16 17:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6d0b19b8-8ba0-4f92-8816-5ac073162e35'), editable=False, primary_key=True, serialize=False),
        ),
    ]
