# Generated by Django 5.0.8 on 2026-01-16 18:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d46b851f-db08-4f85-a708-8a0b110a9cb2'), editable=False, primary_key=True, serialize=False),
        ),
    ]
