# Generated by Django 5.0.8 on 2026-01-16 20:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e92ec792-919e-4884-95e9-3efaed8a7988'), editable=False, primary_key=True, serialize=False),
        ),
    ]
