# Generated by Django 5.0.8 on 2026-01-18 11:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bb4529d8-a7ee-4178-bb26-8fed4eea644f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
