# Generated by Django 5.0.8 on 2026-01-18 18:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3381be7b-2f09-4de2-ab87-80936febe934'), editable=False, primary_key=True, serialize=False),
        ),
    ]
