# Generated by Django 5.0.8 on 2026-01-18 19:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8a7e0d14-221a-4b29-9ab0-a59e1287407d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
