# Generated by Django 5.0.8 on 2026-01-22 17:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('284ba425-c328-405f-9c58-43820ed0d0e4'), editable=False, primary_key=True, serialize=False),
        ),
    ]
