# Generated by Django 5.0.8 on 2026-01-25 18:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7dcb9f24-b6c3-46f3-a068-4b7385e3686c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
