# Generated by Django 5.0.8 on 2026-01-25 19:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('202417f9-3921-494c-b634-81a4dead1ed5'), editable=False, primary_key=True, serialize=False),
        ),
    ]
