# Generated by Django 5.0.8 on 2026-01-26 00:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9e75fee1-cb32-43bd-9835-feaef399bcbf'), editable=False, primary_key=True, serialize=False),
        ),
    ]
