# Generated by Django 5.0.8 on 2026-02-10 13:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('96490137-986d-48a1-8678-dc37cea98659'), editable=False, primary_key=True, serialize=False),
        ),
    ]
