# Generated by Django 5.0.8 on 2026-02-13 22:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0d918164-d7cd-42ad-a556-f0fd66292778'), editable=False, primary_key=True, serialize=False),
        ),
    ]
