# Generated by Django 5.0.8 on 2026-02-17 11:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3bb31259-75be-473e-be20-dcfa79752cd5'), editable=False, primary_key=True, serialize=False),
        ),
    ]
