# Generated by Django 5.0.8 on 2026-02-20 05:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1e4983fb-ba38-46cb-8312-688a88dabe10'), editable=False, primary_key=True, serialize=False),
        ),
    ]
