# Generated by Django 5.0.8 on 2026-02-20 05:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6136443b-9176-4085-8ef3-cb79607806cc'), editable=False, primary_key=True, serialize=False),
        ),
    ]
