# Generated by Django 5.0.8 on 2026-02-20 05:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1a7ca842-b0fe-4324-907e-50338c0146b2'), editable=False, primary_key=True, serialize=False),
        ),
    ]
