# Generated by Django 6.0.2 on 2026-03-01 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_orderitem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_street_address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
